2015/05/27 14:05:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /home/action/workspace/framework/db/CDbConnection.php:399
Stack trace:
#0 /home/action/workspace/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /home/action/workspace/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /home/action/workspace/framework/base/CModule.php(394): CDbConnection->init()
#3 /home/action/workspace/framework/base/CApplication.php(458): CModule->getComponent('db')
#4 /home/action/workspace/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /home/action/workspace/framework/db/ar/CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 /home/action/workspace/framework/db/ar/CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 /home/action/workspace/www/protected/components/UserIdentity.php(17): CActiveRecord->find('LOWER(username)...', Array)
#8 /home/action/workspace/www/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#9 /home/action/workspace/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 /home/action/workspace/framework/validators/CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 /home/action/workspace/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#12 /home/action/workspace/www/protected/controllers/SiteController.php(94): CModel->validate()
#13 /home/action/workspace/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#14 /home/action/workspace/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#15 /home/action/workspace/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#16 /home/action/workspace/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 /home/action/workspace/framework/web/CWebApplication.php(282): CController->run('login')
#18 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#19 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#20 /home/action/workspace/www/index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://mashpy-226500.apse1.nitrousbox.com/index.php?r=site/login
---
2015/05/27 14:06:23 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pksf_test.{{user}}' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `{{user}}`.
in /home/action/workspace/www/protected/components/UserIdentity.php (17)
in /home/action/workspace/www/protected/models/LoginForm.php (52)
in /home/action/workspace/www/protected/controllers/SiteController.php (94)
2015/05/27 14:06:23 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{user}}" for active record class "User" cannot be found in the database.' in /home/action/workspace/framework/db/ar/CActiveRecord.php:2385
Stack trace:
#0 /home/action/workspace/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 /home/action/workspace/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /home/action/workspace/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /home/action/workspace/framework/db/ar/CActiveRecord.php(1461): CActiveRecord->query(Object(CDbCriteria))
#4 /home/action/workspace/www/protected/components/UserIdentity.php(17): CActiveRecord->find('LOWER(username)...', Array)
#5 /home/action/workspace/www/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#6 /home/action/workspace/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#7 /home/action/workspace/framework/validators/CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#8 /home/action/workspace/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#9 /home/action/workspace/www/protected/controllers/SiteController.php(94): CModel->validate()
#10 /home/action/workspace/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#11 /home/action/workspace/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /home/action/workspace/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /home/action/workspace/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /home/action/workspace/framework/web/CWebApplication.php(282): CController->run('login')
#15 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#16 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#17 /home/action/workspace/www/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://mashpy-226500.apse1.nitrousbox.com/index.php?r=site/login
---
2015/05/27 14:07:45 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pksf_test.{{user}}' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `{{user}}`.
in /home/action/workspace/www/protected/components/UserIdentity.php (17)
in /home/action/workspace/www/protected/models/LoginForm.php (52)
in /home/action/workspace/www/protected/controllers/SiteController.php (94)
2015/05/27 14:07:45 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{user}}" for active record class "User" cannot be found in the database.' in /home/action/workspace/framework/db/ar/CActiveRecord.php:2385
Stack trace:
#0 /home/action/workspace/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 /home/action/workspace/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /home/action/workspace/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /home/action/workspace/framework/db/ar/CActiveRecord.php(1461): CActiveRecord->query(Object(CDbCriteria))
#4 /home/action/workspace/www/protected/components/UserIdentity.php(17): CActiveRecord->find('LOWER(username)...', Array)
#5 /home/action/workspace/www/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#6 /home/action/workspace/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#7 /home/action/workspace/framework/validators/CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#8 /home/action/workspace/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#9 /home/action/workspace/www/protected/controllers/SiteController.php(94): CModel->validate()
#10 /home/action/workspace/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#11 /home/action/workspace/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /home/action/workspace/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /home/action/workspace/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /home/action/workspace/framework/web/CWebApplication.php(282): CController->run('login')
#15 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#16 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#17 /home/action/workspace/www/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://mashpy-226500.apse1.nitrousbox.com/index.php?r=site/login
---
2015/05/27 14:09:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /home/action/workspace/framework/db/CDbConnection.php:399
Stack trace:
#0 /home/action/workspace/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /home/action/workspace/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /home/action/workspace/framework/base/CModule.php(394): CDbConnection->init()
#3 /home/action/workspace/framework/base/CApplication.php(458): CModule->getComponent('db')
#4 /home/action/workspace/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /home/action/workspace/framework/db/ar/CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 /home/action/workspace/framework/db/ar/CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 /home/action/workspace/www/protected/components/UserIdentity.php(17): CActiveRecord->find('LOWER(username)...', Array)
#8 /home/action/workspace/www/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#9 /home/action/workspace/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 /home/action/workspace/framework/validators/CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 /home/action/workspace/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#12 /home/action/workspace/www/protected/controllers/SiteController.php(94): CModel->validate()
#13 /home/action/workspace/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#14 /home/action/workspace/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#15 /home/action/workspace/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#16 /home/action/workspace/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 /home/action/workspace/framework/web/CWebApplication.php(282): CController->run('login')
#18 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#19 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#20 /home/action/workspace/www/index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://mashpy-226500.apse1.nitrousbox.com/index.php?r=site/login
---
2015/05/27 14:10:17 [error] [php] Invalid argument supplied for foreach() (/home/action/workspace/framework/db/ar/CActiveRecord.php:2411)
Stack trace:
#0 /home/action/workspace/framework/db/ar/CActiveRecord.php(1355): User->getTableSchema()
#1 /home/action/workspace/framework/db/ar/CActiveRecord.php(1461): User->query()
#2 /home/action/workspace/www/protected/components/UserIdentity.php(17): User->find()
#3 /home/action/workspace/www/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /home/action/workspace/framework/validators/CInlineValidator.php(42): LoginForm->authenticate()
#5 /home/action/workspace/framework/validators/CValidator.php(201): CInlineValidator->validateAttribute()
#6 /home/action/workspace/framework/base/CModel.php(159): CInlineValidator->validate()
#7 /home/action/workspace/www/protected/controllers/SiteController.php(94): LoginForm->validate()
#8 /home/action/workspace/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#9 /home/action/workspace/framework/web/CController.php(308): CInlineAction->runWithParams()
#10 /home/action/workspace/framework/web/CController.php(286): SiteController->runAction()
#11 /home/action/workspace/framework/web/CController.php(265): SiteController->runActionWithFilters()
#12 /home/action/workspace/framework/web/CWebApplication.php(282): SiteController->run()
#13 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController()
#14 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#15 /home/action/workspace/www/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in /home/action/workspace/www/protected/components/UserIdentity.php (17)
in /home/action/workspace/www/protected/models/LoginForm.php (52)
in /home/action/workspace/www/protected/controllers/SiteController.php (94)
2015/05/27 14:15:14 [error] [php] Invalid argument supplied for foreach() (/home/action/workspace/framework/db/ar/CActiveRecord.php:2411)
Stack trace:
#0 /home/action/workspace/framework/db/ar/CActiveRecord.php(1355): User->getTableSchema()
#1 /home/action/workspace/framework/db/ar/CActiveRecord.php(1461): User->query()
#2 /home/action/workspace/www/protected/components/UserIdentity.php(17): User->find()
#3 /home/action/workspace/www/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /home/action/workspace/framework/validators/CInlineValidator.php(42): LoginForm->authenticate()
#5 /home/action/workspace/framework/validators/CValidator.php(201): CInlineValidator->validateAttribute()
#6 /home/action/workspace/framework/base/CModel.php(159): CInlineValidator->validate()
#7 /home/action/workspace/www/protected/controllers/SiteController.php(94): LoginForm->validate()
#8 /home/action/workspace/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#9 /home/action/workspace/framework/web/CController.php(308): CInlineAction->runWithParams()
#10 /home/action/workspace/framework/web/CController.php(286): SiteController->runAction()
#11 /home/action/workspace/framework/web/CController.php(265): SiteController->runActionWithFilters()
#12 /home/action/workspace/framework/web/CWebApplication.php(282): SiteController->run()
#13 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController()
#14 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#15 /home/action/workspace/www/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in /home/action/workspace/www/protected/components/UserIdentity.php (17)
in /home/action/workspace/www/protected/models/LoginForm.php (52)
in /home/action/workspace/www/protected/controllers/SiteController.php (94)
2015/05/27 14:18:22 [error] [php] Invalid argument supplied for foreach() (/home/action/workspace/framework/db/ar/CActiveRecord.php:2411)
Stack trace:
#0 /home/action/workspace/framework/db/ar/CActiveRecord.php(1355): User->getTableSchema()
#1 /home/action/workspace/framework/db/ar/CActiveRecord.php(1461): User->query()
#2 /home/action/workspace/www/protected/components/UserIdentity.php(17): User->find()
#3 /home/action/workspace/www/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /home/action/workspace/framework/validators/CInlineValidator.php(42): LoginForm->authenticate()
#5 /home/action/workspace/framework/validators/CValidator.php(201): CInlineValidator->validateAttribute()
#6 /home/action/workspace/framework/base/CModel.php(159): CInlineValidator->validate()
#7 /home/action/workspace/www/protected/controllers/SiteController.php(94): LoginForm->validate()
#8 /home/action/workspace/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#9 /home/action/workspace/framework/web/CController.php(308): CInlineAction->runWithParams()
#10 /home/action/workspace/framework/web/CController.php(286): SiteController->runAction()
#11 /home/action/workspace/framework/web/CController.php(265): SiteController->runActionWithFilters()
#12 /home/action/workspace/framework/web/CWebApplication.php(282): SiteController->run()
#13 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController()
#14 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#15 /home/action/workspace/www/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/login
in /home/action/workspace/www/protected/components/UserIdentity.php (17)
in /home/action/workspace/www/protected/models/LoginForm.php (52)
in /home/action/workspace/www/protected/controllers/SiteController.php (94)
2015/05/27 14:19:57 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pksf_test.{{user}}' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `{{user}}`.
in /home/action/workspace/www/protected/components/UserIdentity.php (17)
in /home/action/workspace/www/protected/models/LoginForm.php (52)
in /home/action/workspace/www/protected/controllers/SiteController.php (94)
2015/05/27 14:19:57 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{user}}" for active record class "User" cannot be found in the database.' in /home/action/workspace/framework/db/ar/CActiveRecord.php:2385
Stack trace:
#0 /home/action/workspace/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 /home/action/workspace/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /home/action/workspace/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /home/action/workspace/framework/db/ar/CActiveRecord.php(1461): CActiveRecord->query(Object(CDbCriteria))
#4 /home/action/workspace/www/protected/components/UserIdentity.php(17): CActiveRecord->find('LOWER(username)...', Array)
#5 /home/action/workspace/www/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#6 /home/action/workspace/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#7 /home/action/workspace/framework/validators/CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#8 /home/action/workspace/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#9 /home/action/workspace/www/protected/controllers/SiteController.php(94): CModel->validate()
#10 /home/action/workspace/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#11 /home/action/workspace/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /home/action/workspace/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /home/action/workspace/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /home/action/workspace/framework/web/CWebApplication.php(282): CController->run('login')
#15 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#16 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#17 /home/action/workspace/www/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://mashpy-226500.apse1.nitrousbox.com/index.php?r=site/login
---
2015/05/27 14:20:28 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pksf_test.tbl_user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_user`.
in /home/action/workspace/www/protected/components/UserIdentity.php (17)
in /home/action/workspace/www/protected/models/LoginForm.php (52)
in /home/action/workspace/www/protected/controllers/SiteController.php (94)
2015/05/27 14:20:28 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{user}}" for active record class "User" cannot be found in the database.' in /home/action/workspace/framework/db/ar/CActiveRecord.php:2385
Stack trace:
#0 /home/action/workspace/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 /home/action/workspace/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /home/action/workspace/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /home/action/workspace/framework/db/ar/CActiveRecord.php(1461): CActiveRecord->query(Object(CDbCriteria))
#4 /home/action/workspace/www/protected/components/UserIdentity.php(17): CActiveRecord->find('LOWER(username)...', Array)
#5 /home/action/workspace/www/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#6 /home/action/workspace/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#7 /home/action/workspace/framework/validators/CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#8 /home/action/workspace/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#9 /home/action/workspace/www/protected/controllers/SiteController.php(94): CModel->validate()
#10 /home/action/workspace/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#11 /home/action/workspace/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /home/action/workspace/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /home/action/workspace/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /home/action/workspace/framework/web/CWebApplication.php(282): CController->run('login')
#15 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#16 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#17 /home/action/workspace/www/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://mashpy-226500.apse1.nitrousbox.com/index.php?r=site/login
---
2015/05/27 14:28:17 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /home/action/workspace/framework/gii/GiiModule.php:170
Stack trace:
#0 /home/action/workspace/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /home/action/workspace/framework/web/CWebApplication.php(282): CController->run('')
#2 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#4 /home/action/workspace/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=gii
---
2015/05/27 14:35:57 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /home/action/workspace/framework/gii/GiiModule.php:170
Stack trace:
#0 /home/action/workspace/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /home/action/workspace/framework/web/CWebApplication.php(282): CController->run('')
#2 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#4 /home/action/workspace/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=gii
---
2015/05/27 14:39:17 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pksf_test.tbl_post' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_post`.
in /home/action/workspace/www/index.php (13)
2015/05/27 15:03:00 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /home/action/workspace/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /home/action/workspace/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /home/action/workspace/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /home/action/workspace/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /home/action/workspace/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /home/action/workspace/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /home/action/workspace/framework/web/CController.php(291): CFilterChain->run()
#6 /home/action/workspace/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /home/action/workspace/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('jobpost/admin')
#9 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#10 /home/action/workspace/www/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=jobpost/admin
HTTP_REFERER=http://mashpy-226500.apse1.nitrousbox.com/index.php?r=jobpost/index
---
2015/05/27 15:35:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "jopost".' in /home/action/workspace/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#1 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /home/action/workspace/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/
---
2015/05/27 15:39:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in /home/action/workspace/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('index')
#1 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /home/action/workspace/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=index
HTTP_REFERER=http://mashpy-226500.apse1.nitrousbox.com/
---
2015/05/27 15:39:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in /home/action/workspace/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('index')
#1 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /home/action/workspace/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=index
HTTP_REFERER=http://mashpy-226500.apse1.nitrousbox.com/index.php?r=index
---
2015/05/27 15:45:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "jobpost".' in /home/action/workspace/framework/web/CController.php:483
Stack trace:
#0 /home/action/workspace/framework/web/CController.php(270): CController->missingAction('jobpost')
#1 /home/action/workspace/framework/web/CWebApplication.php(282): CController->run('jobpost')
#2 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('jobpost/jobpost')
#3 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#4 /home/action/workspace/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=jobpost/jobpost
HTTP_REFERER=http://mashpy-226500.apse1.nitrousbox.com/
---
2015/05/27 15:46:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index/jobpost".' in /home/action/workspace/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('index/jobpost')
#1 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /home/action/workspace/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=index/jobpost
---
2015/05/27 15:46:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "jobpost".' in /home/action/workspace/framework/web/CController.php:483
Stack trace:
#0 /home/action/workspace/framework/web/CController.php(270): CController->missingAction('jobpost')
#1 /home/action/workspace/framework/web/CWebApplication.php(282): CController->run('jobpost')
#2 /home/action/workspace/framework/web/CWebApplication.php(141): CWebApplication->runController('jobpost/jobpost')
#3 /home/action/workspace/framework/base/CApplication.php(184): CWebApplication->processRequest()
#4 /home/action/workspace/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=jobpost/jobpost
HTTP_REFERER=http://mashpy-226500.apse1.nitrousbox.com/index.php?r=jobpost
---
